const ZONES = {
  U:{name:"Upstairs"},
  M:{name:"Main floor"},
  G:{name:"Garage"},
  O:{name:"Outdoor", desc:"Yard, shed, pool & outdoor kitchen"},
  B:{name:"Basement"}
};
const ZONE_ORDER = ["U","M","G","O","B"];

/* ---------- line-icon set (replaces emoji) ---------- */
const ICONS = {
  box: '<path d="M3 7l9-4 9 4-9 4-9-4z"/><path d="M3 7v10l9 4 9-4V7"/><path d="M12 11v10"/>',
  gear: '<circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M4.2 4.2l2.1 2.1M17.7 17.7l2.1 2.1M2 12h3M19 12h3M4.2 19.8l2.1-2.1M17.7 6.3l2.1-2.1"/>',
  "toilet-paper": '<rect x="5" y="8" width="14" height="12" rx="2"/><ellipse cx="12" cy="8" rx="7" ry="3"/><ellipse cx="12" cy="8" rx="3" ry="1.3"/>',
  pot: '<path d="M4 9h16l-1.5 10.5A2 2 0 0 1 16.5 21h-9a2 2 0 0 1-2-1.5L4 9z"/><path d="M2 6h20"/><path d="M8 6V4h8v2"/>',
  container: '<rect x="4" y="8" width="16" height="12" rx="2"/><path d="M4 8l2-4h12l2 4"/>',
  suitcase: '<rect x="3" y="8" width="18" height="12" rx="2"/><path d="M8 8V6a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/><path d="M3 13h18"/>',
  lock: '<rect x="5" y="11" width="14" height="9" rx="2"/><path d="M8 11V8a4 4 0 0 1 8 0v3"/><circle cx="12" cy="15" r="1.4"/>',
  jar: '<path d="M8 3h8"/><path d="M9 3v3l-2 2v11a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V8l-2-2V3"/><path d="M7 12h10"/>',
  hanger: '<path d="M12 4a2 2 0 1 1 2 2c-.6.6-1 1-1 2"/><path d="M12 8l-9 6h18l-9-6z"/><path d="M3 18h18"/>',
  droplet: '<path d="M12 3s7 7.5 7 12a7 7 0 0 1-14 0c0-4.5 7-12 7-12z"/>',
  dice: '<rect x="4" y="4" width="16" height="16" rx="3"/><circle cx="8.5" cy="8.5" r="1.1" fill="currentColor" stroke="none"/><circle cx="15.5" cy="8.5" r="1.1" fill="currentColor" stroke="none"/><circle cx="8.5" cy="15.5" r="1.1" fill="currentColor" stroke="none"/><circle cx="15.5" cy="15.5" r="1.1" fill="currentColor" stroke="none"/><circle cx="12" cy="12" r="1.1" fill="currentColor" stroke="none"/>',
  wrench: '<path d="M14.7 6.3a4 4 0 0 0-5.4 5.4L3 18l3 3 6.3-6.3a4 4 0 0 0 5.4-5.4l-2.8 2.8-2.4-2.4z"/>',
  fish: '<path d="M3 12s3-5 9-5 9 5 9 5-3 5-9 5-9-5-9-5z"/><circle cx="16" cy="11" r="1" fill="currentColor" stroke="none"/><path d="M3 12l-2-3v6l2-3z"/>',
  glove: '<path d="M8 10V5a1.5 1.5 0 0 1 3 0v4M11 9V4a1.5 1.5 0 0 1 3 0v5M14 9.5V6a1.5 1.5 0 0 1 3 0v7"/><path d="M17 10a2 2 0 0 1 4 0v4a7 7 0 0 1-7 7h-2a7 7 0 0 1-7-7v-3a1.5 1.5 0 0 1 3 0"/>',
  snowflake: '<path d="M12 2v20M5.6 5.6l12.8 12.8M18.4 5.6L5.6 18.4"/>',
  truck: '<path d="M3 7h11v9H3z"/><path d="M14 10h4l3 3v3h-7z"/><circle cx="7" cy="18" r="1.6"/><circle cx="17" cy="18" r="1.6"/>',
  plug: '<path d="M9 2v6M15 2v6M7 8h10v4a5 5 0 0 1-5 5 5 5 0 0 1-5-5V8z"/><path d="M12 17v5"/>',
  bed: '<path d="M3 18v-7a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v7"/><path d="M3 15h18"/><path d="M7 11V7a1 1 0 0 1 1-1h3a1 1 0 0 1 1 1v2"/><path d="M3 21v-3M21 21v-3"/>',
  moon: '<path d="M20 14.5A8.5 8.5 0 1 1 9.5 4a7 7 0 0 0 10.5 10.5z"/>',
  toothbrush: '<path d="M4 20l5-5"/><path d="M9 15l8-8a2.8 2.8 0 0 1 4 4l-8 8z"/><path d="M14 6l4 4"/>',
  leaf: '<path d="M5 21c9 0 14-5 14-16C8 5 3 10 3 19"/><path d="M5 21c3-6 6-10 14-16"/>',
  flask: '<path d="M9 3h6M10 3v6l-5 9a2 2 0 0 0 1.8 3h10.4a2 2 0 0 0 1.8-3l-5-9V3"/><path d="M8 14h8"/>',
  waves: '<path d="M2 8c2-2 4-2 6 0s4 2 6 0 4-2 6 0"/><path d="M2 14c2-2 4-2 6 0s4 2 6 0 4-2 6 0"/><path d="M2 20c2-2 4-2 6 0s4 2 6 0 4-2 6 0"/>',
  utensils: '<path d="M6 2v8a2 2 0 0 0 4 0V2M8 10v12M17 2s-3 1-3 5 1 4 1 4v11"/>',
  flame: '<path d="M12 2s5 4 5 9a5 5 0 0 1-10 0c0-1 .3-2 1-3 .3 1 1 1.5 1.5 1 .5-2-1-3-1-5.5C8.5 2 12 2 12 2z"/>',
  cup: '<path d="M5 8h11v7a5 5 0 0 1-5 5h-1a5 5 0 0 1-5-5V8z"/><path d="M16 9h2a2 2 0 0 1 0 4h-2"/><path d="M8 2v3M12 2v3"/>',
  "ice-cube": '<rect x="5" y="5" width="14" height="14" rx="2"/><path d="M5 9h14M9 5v14"/>',
  sprout: '<path d="M12 22v-9"/><path d="M12 13c-4 0-7-3-7-7 4 0 7 3 7 7z"/><path d="M12 13c4 0 7-3 7-7-4 0-7 3-7 7z"/>',
  home: '<path d="M4 11l8-7 8 7"/><path d="M6 10v9a1 1 0 0 0 1 1h3v-6h4v6h3a1 1 0 0 0 1-1v-9"/>',
  "check-circle": '<circle cx="12" cy="12" r="9"/><path d="M8 12.5l2.5 2.5L16 9.5"/>',
  broom: '<path d="M19 5l-8 8"/><path d="M11 13l-8 8"/><path d="M3 21l2-6 4 4-6 2z"/>',
  chair: '<path d="M6 4v9M18 4v9"/><path d="M6 13h12v3a4 4 0 0 1-4 4h-4a4 4 0 0 1-4-4v-3z"/><path d="M6 20l-1 2M18 20l1 2"/>',
  "help-circle": '<circle cx="12" cy="12" r="9"/><path d="M9.3 9.2a2.7 2.7 0 0 1 5.1 1.2c0 1.8-2.2 1.7-2.2 3.6"/><circle cx="12" cy="17.2" r=".6" fill="currentColor" stroke="none"/>'
};
function icon(key){
  return `<svg width="1em" height="1em" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" style="display:inline-block;vertical-align:-0.15em" aria-hidden="true">${ICONS[key]||ICONS.box}</svg>`;
}

const RAW_LOCATIONS = [
  {code:"B1",icon:"box",name:"Basement Storage Room",job:"Long-term household storage",
   items:["Christmas décor","Memories","Photo albums","Kids' keepsakes","Office supplies","Craft supplies","Party supplies","Gift supplies","Long-term electronics","Spare household supplies","Paint overflow","Repair overflow"],
   maybe:["Halloween & Easter decor","Wrapping paper & gift bags","Wedding keepsakes","Old yearbooks","Baby items being saved","Extra light bulbs & batteries"],
   kw:"christmas halloween easter thanksgiving decorations ornaments wreath lights tinsel garland keepsake memento memorabilia scrapbook yearbook wedding baby book trophy award diploma craft scrapbooking wrapping paper gift bag ribbon greeting card stationery office supply printer paper binder file folder old phone old laptop router spare paint touch up caulk tube lightbulb spare battery spare"},
  {code:"B2",icon:"gear",name:"Mechanical Room",job:"House mechanical supplies only",
   items:["HVAC filters","Air filters","Humidifier filters","House-system replacement items"],
   maybe:["Appliance manuals","Sump pump parts","Water softener salt","Smoke detector batteries"],
   kw:"furnace filter air filter hvac filter humidifier filter water filter cartridge water heater sump pump well pump thermostat battery smoke detector battery carbon monoxide detector appliance manual warranty paperwork"},
  {code:"B3",icon:"toilet-paper",name:"Basement Bathroom",job:"Basement bathroom supplies",
   items:["Toilet paper","Soap","Cleaning backups","Toiletry backups"],maybe:["Plunger","Extra hand towels","Air freshener","Night light"],
   kw:"toilet paper soap plunger toilet brush air freshener night light hand towel"},
  {code:"B4",icon:"pot",name:"Basement Kitchen",job:"Specialty kitchen appliances & extra cookware",
   items:["Stock pot","Fondue pot","Wok","Electric griddle","Panini maker","Roasting pans","Food processor","Slow cookers","Keurig","Shaved-ice machine","Waffle maker","Electric skillet"],
   maybe:["Turkey fryer","Bread machine","Pasta maker","Ice cream maker","Pressure canner","Holiday baking pans"],
   kw:"stock pot fondue wok griddle panini press roasting pan food processor slow cooker crockpot instant pot keurig coffee maker waffle maker deep fryer turkey fryer bread machine pasta maker ice cream maker pressure canner mixer blender specialty appliance"},
  {code:"B5",icon:"container",name:"Basement Kitchen Peninsula",job:"Entertaining & food-storage overflow",
   items:["Tupperware","Bento boxes","Party trays","Plasticware","Paper bowls","Paper cups","Paper plates","Serving pieces"],
   maybe:["Coolers","Drink dispenser","Chafing dishes","Disposable cutlery","Punch bowl"],
   kw:"tupperware food container bento box party tray plasticware disposable plate disposable cup paper plate paper bowl serving dish platter cooler drink dispenser chafing dish punch bowl cocktail supply"},
  {code:"B6",icon:"suitcase",name:"Under-Stairs Storage",job:"Bulky travel & camping storage",
   items:["Suitcases","Sleeping bags","Cots","Packing cubes","Camping gear","Slackline","Inflatable pump","Travel cooking equipment"],
   maybe:["Tents","Camp chairs","Hiking backpacks","Sleeping pads","Road-trip games"],
   kw:"suitcase luggage duffel bag sleeping bag tent camp chair camping stove travel cooler packing cube travel pillow hiking backpack sleeping pad road trip"},
  {code:"B7",icon:"lock",name:"Safe",job:"Important documents & valuables",
   items:["Passports","Important documents","Checkbooks","Records"],
   maybe:["Jewelry","Backup hard drives","Spare house keys","Will & estate papers"],
   kw:"passport birth certificate social security card will deed title jewelry cash external hard drive backup spare key important document valuables"},

  {code:"M1",icon:"pot",name:"Main Kitchen",job:"Everyday kitchen & frequently used appliances",
   items:["KitchenAid (appliance lift)","Everyday cookware","Baking tools","Fridge filters","Everyday food storage","Rubberware / food containers"],
   maybe:["Blender","Toaster","Everyday dishware","Cutting boards","Spice rack"],
   kw:"blender toaster mixer cutting board dish plate pan pot spice measuring cup kitchenaid fridge filter everyday cookware rubberware rubbermaid tupperware food container lid leftovers bread baking dough yeast banneton proofing bench scraper lame loaf pan dutch oven kitchen scale dough whisk"},
  {code:"M2",icon:"jar",name:"Pantry",job:"Food & consumables",
   items:["Pantry staples","Bulk food","Snacks","Paper food products","Food backups"],
   maybe:["Cereal","Coffee & tea","Cooking oils","Kids' snacks","Canned goods"],
   kw:"cereal snack canned food pasta rice coffee tea cooking oil condiment flour sugar pantry staple bulk food"},
  {code:"M3",icon:"hanger",name:"Entry Coat Closet",job:"Things you grab when leaving",
   items:["Shoes","Gloves","Hats","Scarves","Umbrellas","Coats","Bags"],
   maybe:["Backpacks","Sunglasses","Reusable shopping bags","Sunscreen","Leashes"],
   kw:"coat jacket shoe boot glove hat scarf umbrella backpack sunglasses reusable bag mask sunscreen leash keys"},
  {code:"M4",icon:"toilet-paper",name:"Main-Floor Bathroom",job:"Guest & main-floor bathroom supplies",
   items:["Toilet paper","Hand soap","Toiletries","Cleaners"],maybe:["Guest towels","Hand lotion","Extra toilet paper","Air freshener"],
   kw:"toilet paper hand soap guest towel air freshener bathroom guest"},
  {code:"M5",icon:"droplet",name:"Laundry Room",job:"Cleaning, laundry & household refills",
   items:["Detergent","Dryer sheets","OxiClean","Febreze","Glass cleaner","Shout","Pledge","Upholstery supplies","Handheld vacuum","Rags","Towels","Pool & beach towels"],
   maybe:["Iron & board","Mop & broom","Lint roller","Stain stick","Trash bags"],
   kw:"detergent dryer sheet oxiclean febreze glass cleaner windex stain remover iron ironing board mop broom handheld vacuum trash bag dish soap sponge rag upholstery cleaner lint roller laundry cleaning supply"},
  {code:"M6",icon:"dice",name:"Game Room Built-Ins",job:"Games, recreation & family fun",
   items:["Pokémon cards","Puzzles","Costumes","Dress-up items","Laser tag","Indoor games","Books"],
   maybe:["Board games","Playing cards","Legos","Art supplies","Remote controls"],
   kw:"board game card game puzzle costume dress up laser tag lego remote control book toy indoor pokemon"},

  {code:"G1",icon:"wrench",name:"Workbench & Tool Cabinets",job:"Tools, hardware & repair supplies",
   items:["Reciprocating saw","Skill saw","Sander","Levels","Stud finder","Nuts","Bolts","Screws","Anchors","Tape","Caulk","Adhesives","Vacuum parts","Small repair pieces"],
   maybe:["Drill batteries","Extension cords","Work gloves","Safety glasses","WD-40"],
   kw:"drill saw sander level stud finder screw bolt nut anchor tape measure caulk adhesive glue wrench screwdriver hammer pliers extension cord work glove safety glasses wd40 hardware tool repair glue gun staple gun nail gun heat gun caulk gun"},
  {code:"G2",icon:"fish",name:"Tall Utility Cabinet 1",job:"Outdoor & recreation gear",
   items:["Fishing gear","Tackle","Nets","Waders","Outdoor equipment"],maybe:["Bike helmets","Life jackets","Sports balls","Fishing licenses","Airsoft & BB guns","Nerf blasters","Bow & arrows"],
   kw:"fishing rod tackle net waders bike helmet life jacket sports ball fishing license outdoor recreation gear airsoft bb gun nerf blaster pellet gun bow arrow ammo eye protection safety goggles hunting archery"},
  {code:"G3",icon:"glove",name:"Small Cabinet by Backyard Door",job:"Quick-grab garage supplies",
   items:["Small repair supplies","Tapes","Cords","Gloves","Everyday garage & backyard items"],
   maybe:["Bug spray","Sunscreen","Gardening gloves","Water bottles"],
   kw:"bug spray sunscreen gardening glove water bottle small extension cord quick grab backyard"},
  {code:"G4",icon:"snowflake",name:"Garage Fridge & Freezer",job:"Food & drink overflow",
   items:["Frozen foods","Drinks","Cookout supplies","Overflow fridge items"],maybe:["Bulk meat","Holiday leftovers","Extra milk","Party ice"],
   kw:"frozen food bulk meat extra drink party ice holiday leftovers extra milk freezer overflow"},
  {code:"G5",icon:"truck",name:"Tall Utility Cabinet 2",job:"Bulky garage gear",
   items:["Tarps","Covers","Shoulder dolly","Large outdoor items","Car items","Awkward equipment"],
   maybe:["Snow shovels","Small ladder","Holiday inflatables","Car ramps"],
   kw:"tarp cover shoulder dolly snow shovel small ladder car ramp holiday inflatable bulky"},

  {code:"U1",icon:"hanger",name:"West Bedroom Closet",job:"That bedroom's personal storage",
   items:["Clothing","Shoes","Personal items","Keepsakes (modest)"],maybe:["Off-season clothing","Extra pillows","Hobby supplies","Board games"],
   kw:"clothing shoes personal item hobby supply extra pillow off season clothing bedroom closet"},
  {code:"U2",icon:"toilet-paper",name:"Hall Bathroom Storage",job:"Family bathroom & linen storage",
   items:["Towels","Spare toiletries","Toilet paper","Bathroom backups"],maybe:["Bath toys","First-aid kit","Extra shampoo","Nail clippers"],
   kw:"towel shampoo bath toy first aid nail clipper hall bathroom linen"},
  {code:"U3",icon:"plug",name:"Master Bedroom Left Built-In",job:"Personal tech",
   items:["Charging blocks","USB cords","Headphones","Earbuds","Tablets","Kindle","Laptops","Charging station"],
   maybe:["Old phones","Camera gear","Game controllers","Spare batteries"],
   kw:"charger cable headphone earbud tablet kindle laptop old phone camera game controller spare battery personal tech"},
  {code:"U4",icon:"bed",name:"Master Bedroom Window Drawers",job:"Master linens & soft goods",
   items:["Bedding","Blankets","Comforters","Throws","Spare sheets"],maybe:["Mattress pad","Pillow protectors","Extra pillows"],
   kw:"bedding blanket comforter throw sheet mattress pad pillow protector linens"},
  {code:"U5",icon:"moon",name:"Master Bedroom Right Built-In",job:"Bedroom comfort & occasional-use items",
   items:["White-noise machines","Humidifiers","Diffusers","Headlamps"],maybe:["Extra blankets","Sleep mask","Diffuser refills","Night light"],
   kw:"white noise machine humidifier diffuser headlamp sleep mask night light bedroom comfort"},
  {code:"U6",icon:"toothbrush",name:"Master Bathroom Vanity",job:"Daily grooming & personal care",
   items:["Toothbrush items","Grooming tools","Deodorant","Cologne","Mouthwash","Lotion","Hair products","Skin care","Makeup","Q-tips","Nail supplies"],
   maybe:["First-aid supplies","Contact solution","Hair dryer","Electric razor"],
   kw:"toothbrush deodorant cologne perfume mouthwash lotion hair product makeup qtip nail supply razor first aid contact lens hair dryer grooming"},
  {code:"U7",icon:"hanger",name:"Master Closet",job:"Adult clothing & accessories",
   items:["Seasonal clothing","Ski gear","Chacos","Suits","Ties","Dresses","Army uniforms","Formalwear","Shoes"],
   maybe:["Handbags","Belts","Jewelry organizer","Out-of-season shoes"],
   kw:"suit tie dress formalwear uniform ski gear chacos handbag belt jewelry out of season shoe adult clothing"},
  {code:"U8",icon:"hanger",name:"East Bedroom Closet",job:"That bedroom's personal storage",
   items:["Clothing","Shoes","Personal belongings","Bedroom keepsakes"],maybe:["Off-season clothing","Extra pillows","Hobby supplies","Board games"],
   kw:"clothing shoes personal item hobby supply extra pillow off season clothing bedroom closet"},

  {code:"O1",icon:"leaf",name:"Shed",job:"Yard & outdoor equipment",
   items:["Lawn tools","Outdoor games","Tarps","Outdoor fishing items","Garden gear"],
   maybe:["Wheelbarrow","Hose","Bike pump","Extension cords"],
   kw:"lawn tool rake shovel mower wheelbarrow hose bike pump garden tool outdoor game extension cord yard"},
  {code:"O2",icon:"flask",name:"Shed Chemical Cabinet",job:"Lawn & garden chemicals",
   items:["Roundup","Insect killer","Plant food","Grass seed","Yard products"],maybe:["Ice melt","Mosquito spray","Wood stain","Motor oil"],
   kw:"roundup weed killer insect killer fertilizer grass seed ice melt mosquito spray wood stain motor oil chemical"},
  {code:"O3",icon:"waves",name:"Pool Storage Enclosure",job:"Pool gear",
   items:["Pool bags","Pool accessories","Pool nets","Covers","Hot-tub filters","Pool filters","Pool-use equipment"],
   maybe:["Pool toys","Floaties","Pool towels","Skimmer net"],
   kw:"pool toy floatie pool towel skimmer net pool vacuum hot tub cover pool bag"},
  {code:"O4",icon:"container",name:"Pool Equipment / Seasonal Cabinet",job:"Outdoor pool accessories and label-approved seasonal supplies",
   items:["Pool testing accessories","Maintenance accessories","Small pool equipment"],maybe:["Skimmer parts","Hose fittings","Seasonal pool accessories"],
   kw:"pool equipment skimmer hose fitting testing accessory maintenance accessory seasonal pool"},
  {code:"O5",icon:"utensils",name:"Outdoor Kitchen Cabinet",job:"Outdoor entertaining supplies",
   items:["Outdoor serving pieces","Cups","Plates","Paper goods","Towels","Grilling backup supplies"],maybe:["Tablecloths","Citronella candles","Chair cushions"],
   kw:"tablecloth citronella candle outdoor cup outdoor plate chair cushion entertaining"},
  {code:"O6",icon:"flame",name:"Outdoor Kitchen Drawers",job:"Grilling tools",
   items:["Tongs","Spatulas","Thermometers","Skewers","Foil","Grill utensils"],maybe:["Grill brush","Meat thermometer","Grill cover","Charcoal"],
   kw:"grill brush meat thermometer grill cover charcoal tongs spatula skewer grilling"},
  {code:"O7",icon:"cup",name:"Outdoor Kitchen Fridge",job:"Outdoor food & drinks",
   items:["Drinks","Condiments","Cookout food"],maybe:["Extra condiments","Popsicles","Bottled water"],
   kw:"condiment popsicle bottled water outdoor drink"},
  {code:"O8",icon:"ice-cube",name:"Outdoor Kitchen Ice Maker",job:"Ice only",items:["Ice"],maybe:[],
   kw:"ice"}
];


const SUBLOCATIONS = [
  {code:"B1-A",location:"B1",name:"Shelves A · 1–8",notes:"Seasonal décor and holiday bins"},
  {code:"B1-B",location:"B1",name:"Shelves B · 9–16",notes:"Keepsakes, photos, kids memories"},
  {code:"B1-C",location:"B1",name:"Shelves C · 17–24",notes:"Office, craft, party, gift and household backups"},
  {code:"B1-D",location:"B1",name:"Network / security overhead",notes:"Router, NVR and house-system equipment only"},
  {code:"B2-A",location:"B2",name:"Filter shelf",notes:"HVAC, humidifier and house-system filters"},
  {code:"B2-B",location:"B2",name:"System parts / manuals",notes:"House-system replacement parts, manuals and maintenance pieces"},
  {code:"B3-A",location:"B3",name:"Vanity",notes:"Basement bathroom supplies"},
  {code:"B4-A",location:"B4",name:"Upper cabinets",notes:"Lighter specialty kitchen items"},
  {code:"B4-B",location:"B4",name:"Base cabinets",notes:"Large specialty appliances and cookware"},
  {code:"B4-C",location:"B4",name:"Drawers",notes:"Smaller kitchen tools and accessories"},
  {code:"B4-D",location:"B4",name:"Pull-outs",notes:"Accessible specialty kitchen storage"},
  {code:"B5-A",location:"B5",name:"Peninsula cabinets",notes:"Entertaining and serving overflow"},
  {code:"B5-B",location:"B5",name:"Food-storage overflow",notes:"Extra Rubberware, bento boxes, lids and party food-storage pieces"},
  {code:"B6-A",location:"B6",name:"Luggage zone",notes:"Suitcases, travel bags and packing accessories"},
  {code:"B6-B",location:"B6",name:"Camping sleep gear",notes:"Sleeping bags, cots and soft camping gear"},
  {code:"B6-C",location:"B6",name:"Camping / adventure gear",notes:"Pumps, slackline, camp kitchen and outdoor travel gear"},
  {code:"B7-A",location:"B7",name:"Documents",notes:"Passports, checkbooks and important records"},
  {code:"B7-B",location:"B7",name:"Valuables / backups",notes:"Small valuables, spare keys and secure backups"},
  {code:"M1-A",location:"M1",name:"Appliance lift",notes:"KitchenAid"},
  {code:"M1-B",location:"M1",name:"Cooktop drawers",notes:"Cooking tools and utensils"},
  {code:"M1-C",location:"M1",name:"Cooktop base cabinets",notes:"Everyday pots and pans"},
  {code:"M1-D",location:"M1",name:"Sink base",notes:"Dish and sink supplies"},
  {code:"M1-E",location:"M1",name:"Island drawers",notes:"Everyday utensils and prep tools"},
  {code:"M1-F",location:"M1",name:"Food storage / Rubberware",notes:"Everyday Rubbermaid, Tupperware, food containers and matching lids"},
  {code:"M1-G",location:"M1",name:"Vertical dividers",notes:"Cutting boards and sheet pans"},
  {code:"M1-H",location:"M1",name:"Baking Corner · Left Cabinet",notes:"Bread-making bowls, proofing gear, baking pans and heavier baking equipment beside the sink"},
  {code:"M1-L",location:"M1",name:"Baking Corner · Pull-Out Drawers",notes:"Small bread and baking tools kept directly under the baking counter"},
  {code:"M1-I",location:"M1",name:"Upper cabinets",notes:"Dishware and lighter kitchen items"},
  {code:"M1-J",location:"M1",name:"High cabinets",notes:"Rarely used kitchen items"},
  {code:"M1-K",location:"M1",name:"Fridge-side storage",notes:"Fridge filters and food-related backups"},
  {code:"M2-A",location:"M2",name:"Shallow shelves",notes:"Everyday food and easy-to-see pantry staples"},
  {code:"M2-B",location:"M2",name:"Deep shelves",notes:"Bulk food and backstock in labeled bins"},
  {code:"M2-C",location:"M2",name:"Lower / floor area",notes:"Drinks and large pantry items"},
  {code:"M3-A",location:"M3",name:"Hanging rail",notes:"Coats and jackets"},
  {code:"M3-B",location:"M3",name:"Shelf stack",notes:"Hats, gloves, scarves and grab-and-go items"},
  {code:"M3-C",location:"M3",name:"Floor / shoe area",notes:"Shoes and boots"},
  {code:"M4-A",location:"M4",name:"Vanity",notes:"Guest and main-floor bathroom supplies"},
  {code:"M5-A",location:"M5",name:"Tall cabinet · shelves",notes:"Spa/pool supplies whose labels permit conditioned indoor storage"},
  {code:"M5-B",location:"M5",name:"Tall cabinet · drawers",notes:"Pool/spa testing gear and accessories"},
  {code:"M5-C",location:"M5",name:"Above washer / dryer",notes:"Rarely used lightweight backups only"},
  {code:"M5-D",location:"M5",name:"Upper left of sink",notes:"Cleaning supplies"},
  {code:"M5-E",location:"M5",name:"Upper right of sink",notes:"Household backups and utility supplies"},
  {code:"M5-F",location:"M5",name:"Left sink drawers",notes:"Cleaning tools and rags"},
  {code:"M5-G",location:"M5",name:"Right sink drawers",notes:"Laundry and garment care"},
  {code:"M5-H",location:"M5",name:"Under sink",notes:"Sink-related cleaning only; keep sparse"},
  {code:"M5-I",location:"M5",name:"Lower cabinets",notes:"Pool towels, cleaning towels and bulky cleaning gear"},
  {code:"M6-A",location:"M6",name:"Left built-in bank",notes:"Board games and family games"},
  {code:"M6-B",location:"M6",name:"Right built-in bank",notes:"Books and recreation"},
  {code:"M6-C",location:"M6",name:"Lower storage",notes:"Kids games, costumes and laser tag"},
  {code:"G1-A",location:"G1",name:"Pegboard / worktop",notes:"Frequently used hand tools and active projects"},
  {code:"G1-B",location:"G1",name:"Upper cabinets",notes:"Lightweight repair supplies and less-used tools"},
  {code:"G1-C",location:"G1",name:"Drawer 1",notes:"Small hand tools"},
  {code:"G1-D",location:"G1",name:"Drawer 2",notes:"Measuring, bits and blades"},
  {code:"G1-E",location:"G1",name:"Drawer 3",notes:"Hardware and repair pieces"},
  {code:"G1-F",location:"G1",name:"Drawer 4",notes:"Tool accessories and overflow"},
  {code:"G1-G",location:"G1",name:"Left lower cabinet",notes:"Power tools and larger cases"},
  {code:"G1-H",location:"G1",name:"Right lower cabinet",notes:"Larger repair and tool gear"},
  {code:"G2-A",location:"G2",name:"Upper shelf",notes:"Smaller outdoor/recreation gear"},
  {code:"G2-B",location:"G2",name:"Open center",notes:"Tall or awkward recreation gear"},
  {code:"G2-C",location:"G2",name:"Lower shelf",notes:"Heavier outdoor/recreation gear"},
  {code:"G3-A",location:"G3",name:"Upper shelf",notes:"Quick-grab garage supplies"},
  {code:"G3-B",location:"G3",name:"Lower shelf",notes:"Heavier quick-grab supplies"},
  {code:"G4-A",location:"G4",name:"Refrigerator",notes:"Drinks and refrigerated overflow"},
  {code:"G4-B",location:"G4",name:"Freezer",notes:"Frozen food and bulk meat"},
  {code:"G5-A",location:"G5",name:"Upper shelf",notes:"Lighter bulky-garage accessories"},
  {code:"G5-B",location:"G5",name:"Open center",notes:"Awkward or tall garage gear"},
  {code:"G5-C",location:"G5",name:"Lower shelf",notes:"Heavy bulky garage gear"},
  {code:"U1-A",location:"U1",name:"Shelves",notes:"Folded clothes and personal storage"},
  {code:"U1-B",location:"U1",name:"Hanging section",notes:"Hanging clothes"},
  {code:"U1-C",location:"U1",name:"Floor area",notes:"Shoes and bulky bedroom items"},
  {code:"U2-A",location:"U2",name:"Tall cabinet",notes:"Towels and bathroom backups"},
  {code:"U2-B",location:"U2",name:"Vanity drawers / cabinets",notes:"Daily family bathroom items"},
  {code:"U2-C",location:"U2",name:"Under sink",notes:"Bathroom cleaning supplies"},
  {code:"U3-A",location:"U3",name:"Shelves",notes:"Personal tech and charging station"},
  {code:"U3-B",location:"U3",name:"Drawers",notes:"Cords, chargers, headphones and small tech"},
  {code:"U4-A",location:"U4",name:"Left window drawer",notes:"Sheets"},
  {code:"U4-B",location:"U4",name:"Center window drawer",notes:"Blankets and throws"},
  {code:"U4-C",location:"U4",name:"Right window drawer",notes:"Comforters and bulky soft goods"},
  {code:"U5-A",location:"U5",name:"Shelves",notes:"Sleep and comfort devices"},
  {code:"U5-B",location:"U5",name:"Drawers",notes:"Bedroom comfort accessories and backups"},
  {code:"U6-A",location:"U6",name:"Left vanity",notes:"Daily grooming"},
  {code:"U6-B",location:"U6",name:"Center drawers",notes:"Hair and skincare"},
  {code:"U6-C",location:"U6",name:"Right vanity",notes:"Daily personal care"},
  {code:"U6-D",location:"U6",name:"Under-sink storage",notes:"Bathroom backups"},
  {code:"U7-A",location:"U7",name:"Hanging sections",notes:"Everyday clothes, formalwear and uniforms"},
  {code:"U7-B",location:"U7",name:"Left drawer bank",notes:"Folded clothes"},
  {code:"U7-C",location:"U7",name:"Right drawer bank",notes:"Folded clothes"},
  {code:"U7-D",location:"U7",name:"Corner shelf tower",notes:"Shoes and accessories"},
  {code:"U7-E",location:"U7",name:"Above washer / dryer",notes:"Lightweight laundry backups"},
  {code:"U7-F",location:"U7",name:"Sink cabinets",notes:"Clothing care and laundry supplies"},
  {code:"U8-A",location:"U8",name:"Shelves",notes:"Folded clothes and personal storage"},
  {code:"U8-B",location:"U8",name:"Hanging section",notes:"Hanging clothes"},
  {code:"U8-C",location:"U8",name:"Floor area",notes:"Shoes and bulky bedroom items"},
  {code:"O1-A",location:"O1",name:"Long FastTrack rail",notes:"Frequently used yard tools"},
  {code:"O1-B",location:"O1",name:"Short FastTrack rail",notes:"Smaller hanging outdoor gear"},
  {code:"O1-C",location:"O1",name:"Workbench",notes:"Outdoor projects and tool staging"},
  {code:"O1-D",location:"O1",name:"Wall cabinet",notes:"Small outdoor supplies"},
  {code:"O1-E",location:"O1",name:"Floor / bulk area",notes:"Large yard and outdoor equipment"},
  {code:"O2-A",location:"O2",name:"Lawn / weed control",notes:"Lawn and weed-control products in original containers"},
  {code:"O2-B",location:"O2",name:"Garden / plant care",notes:"Plant food, grass seed and garden-care products"},
  {code:"O4-A",location:"O4",name:"Testing & small equipment",notes:"Pool testing accessories and small maintenance equipment"},
  {code:"O4-B",location:"O4",name:"Seasonal fittings",notes:"Hose fittings, skimmer parts and seasonal pool accessories"},
  {code:"O3-A",location:"O3",name:"Open bulk area",notes:"Pool gear, covers, toys and bulky accessories"},
  {code:"O3-B",location:"O3",name:"Filter / equipment area",notes:"Pool and hot-tub filters and equipment"},
  {code:"O5-A",location:"O5",name:"Tall cabinet shelves",notes:"Outdoor serving and entertaining supplies"},
  {code:"O6-A",location:"O6",name:"Drawer 1",notes:"Grill tools"},
  {code:"O6-B",location:"O6",name:"Drawer 2",notes:"Thermometers, skewers and small accessories"},
  {code:"O6-C",location:"O6",name:"Drawer 3",notes:"Foil and grilling backups"}
];

const SUBLOCATION_ITEMS = {
  "B1-A":["Stocking hangers","Christmas lights","Ornaments","Christmas tree apron / tree skirt","Nativity","Stockings","Christmas toilet seat cover","Harry Potter village set boxes","Decorative lanterns"],
  "B1-B":["Norway memories","Journals","Annie childhood school memories","Encouraging notes","Decorated mug and plates","Frames","Pictures","Photo albums","Family notes","Kids memories","Childhood artwork","School projects","Baby photos","Milestone keepsakes","Kids crafts"],
  "B1-C":["Stapler","Hole punchers","Folders","Paper","Scotch tape","Craft paints","Paint brushes","Post-it notes","Postcards","Highlighters","Dry erase markers","Rubber bands","Trapper Keepers","Construction paper","Dry erase boards","Shredder","Musical instrument tuners","Paper slicer / cutter","Party bags","Tissue paper","Treat bags","Teacher delivery box","Gift bags","Power cords","Wireless USB adapter","Stereo wires","Older laptops / Chromebook","Headphones","iPad holder","Wireless controller","Apple TV","HDMI cords","Ziploc bags","Sandwich bags","Gallon bags","Vacuum seal bags","Lightbulbs","Nightlight bulbs","Switches","Space-saver bags","Space heater","Indoor grow light"],
  "B2-A":["Air filter","Humidifier filter","Miscellaneous house filter"],
  "B2-B":["House-system replacement parts","Appliance maintenance pieces"],
  "B4-A":["Spice grinder","Coffee grinder","Cookie cutter set","Tortilla maker","Onion chopper","Vegetable chopper"],
  "B4-B":["Stock pot","Steaming basket","Sous vide container","Fondue pot","Wok","Electric griddle","Griddle grill","Panini maker","Roasting pan","Waffle griddle","Roasting tins","Food processor","Extra pans","Blender","Ice cream maker","Pressure cooker","Slow cookers / crockpots","Keurig","Coffee maker","Roaster","Hawaiian shaved-ice machine","Waffle maker","Electric skillet"],
  "B4-C":["Kitchen tools","Specialty cooking utensils"],
  "B5-A":["Hosting bowls","Serving trays","Plasticware","Paper bowls","Plastic cups","Paper plates","Party trays","Charcuterie tray","Wine-making equipment","CO₂ tank"],
  "B5-B":["Extra Tupperware / Rubberware","Extra bento boxes","Container dividers","Extra food containers","Reusable lunch containers","Party-size food-storage pieces"],
  "B6-A":["Suitcases","Travel bags","Packing cubes","Camera bag used for travel"],
  "B6-B":["Sleep sack","Cots","Sleeping bags","Compression bag"],
  "B6-C":["Backpack","Slackline","Inflatable pump","Travel cooking gear","Camping gear","Hiking gear"],
  "B7-A":["Passports","Important documents","Checkbooks"],
  "M1-A":["KitchenAid"],
  "M1-F":["Tupperware / Rubberware","Bento boxes","Container dividers","Food containers","Reusable containers","Lunch containers"],
  "M1-G":["Sheet pans","Flat baking pieces"],
  "M1-H":["Baking tins","Roasting tins","Cookie cutter set","Large mixing bowls"],
  "M1-L":["Measuring cups","Measuring spoons","Small baking tools"],
  "M1-K":["Fridge filter"],
  "M3-B":["Gloves","Hats","Scarves","Umbrella"],
  "M3-C":["Shoes"],
  "M5-A":["Hot-tub chemicals (only if each product label permits conditioned indoor storage)"],
  "M5-B":["Pool accessories","Pool testing accessories"],
  "M5-D":["Simple Green","OxiClean","Febreze","Contact cleaner","Glass cleaner","Shout","Pledge","Wood cleaner","Carpet cleaner","Upholstery cleaner","Toilet bowl cleaner","Mrs. Meyer's cleaner","Multipurpose spray","Disinfectant spray","Vinyl cleaner"],
  "M5-E":["Paper towels","Household backup bags","Washer replacement / maintenance pieces"],
  "M5-F":["Rags","Norwex duster"],
  "M5-G":["Detergent","Dryer sheets","Iron","Sweater shaver","Fabric protection products"],
  "M5-I":["Beach towels","Pool towels","Bulky cleaning supplies"],
  "M6-A":["Pokémon cards","Puzzles"],
  "M6-B":["Escape-room items","Collectible / hobby items"],
  "M6-C":["Dress-up clothes","Costume shoes","Costumes","Masks","Boxing gloves","Toy sword","Laser tag equipment"],
  "G1-A":["Frequently used hand tools"],
  "G1-C":["Small screwdriver","Glasses repair screwdriver","Small hand tools"],
  "G1-D":["Level","Stud finder","Utility blades","Tire gauge"],
  "G1-E":["Nuts","Washers","Brackets","O-rings","Metric bolts","Metric screws","Small screws","Staples","Nails","Wall anchors","Large anchor screws","Micro screws","Watch screws","Glasses screws","Tire valve","Tire pump valve","Spark plug","Upholstery buttons"],
  "G1-F":["Bungee cords","Shelving accessories","Car paint pens","Electrical tape","Cable concealer","Gaffer tape","Adhesive","Silicone caulk","Magnet adhesive","Waterproof tape","Vacuum parts","Submersible pump accessories","Drum liner bags","Painter's tape","Spackling","Drywall-repair supplies"],
  "G1-G":["Reciprocating saw","Skill saw","Sander","Power-tool cases"],
  "G1-H":["Shoulder dolly","Larger repair gear"],
  "G2-A":["Tacklebox","Fishing accessories","Can Jam","Spikeball"],
  "G2-B":["Fishing net","Waders"],
  "G2-C":["Fishing gear","Heavier outdoor recreation gear"],
  "G5-A":["Tarp / waterproof cover"],
  "G5-B":["Awkward bulky garage gear"],
  "U3-A":["Tablets","Kindle","Laptops","Camera","Camera lenses","Gameboy","Portable speaker"],
  "U3-B":["USB-C cords","Micro-USB cords","HDMI cords","Charging blocks","Smart plugs","Charging station","Headphones","Earbuds","Headlamps","Waterproof phone case","Batteries","Nightlight","Camera charger","Mouse","Watch batteries"],
  "U4-A":["Fitted sheets","Sheets","Pillowcases","Mattress cover"],
  "U4-B":["Blankets","Egyptian blankets","Throws"],
  "U4-C":["Comforters","Bed covers","Quilts","Bulky bedding"],
  "U5-A":["Noisemakers / sound machines","White-noise devices","Humidifiers","Diffusers"],
  "U5-B":["Sleep accessories","Diffuser accessories"],
  "U6-A":["Toothbrush heads","Toothbrush chargers","Stone file","Combs","Scissors","Hair scissors","Deodorant","Cologne","Hair clippers","Scalp massager"],
  "U6-B":["Rubbing alcohol","Listerine","Lotion","Hair supplies","Hairspray","Gel","Elsie's hair supplies","Q-tips","Sunblock","Lotions","Scrubs","Annie's fragrance","Skin care","Makeup"],
  "U6-C":["Maxi pads","Tampons","Supplements","Vitamins","Capsules","Powders","Capsule maker"],
  "U6-D":["Blow dryer","Hair dye","Nail-polish remover","Nail supplies","Extra loofah","Floss sticks","Chapstick","Bobby pins","Nail clippers","Hair ties"],
  "U7-A":["Suits","Ties","Dresses","Army uniforms","Formalwear"],
  "U7-B":["Seasonal folded clothing","Ski socks","Down vest"],
  "U7-D":["Ski gloves","Ski mask","Chaco sandals","Seasonal accessories"],
  "O2-A":["Roundup / weed killer","Insect killer"],
  "O2-B":["All-purpose plant food","Grass seed"],
  "O3-A":["Pool bag","Beach bag","Pool accessories","Pool-use gear"],
  "O3-B":["Hot-tub filter"],
  "O4-A":["Pool testing accessories","Small pool maintenance accessories"],
  "O4-B":["Pool fittings / seasonal accessories"],
  "O5-A":["Outdoor serving pieces","Outdoor cups / plates when moved outside for the season"],
  "O6-A":["Grill tools"],
  "O6-B":["Thermometers","Skewers"],
  "O6-C":["Foil and grill backups"]
};

const SUBLOCATION_SUGGESTIONS = {
  "B1-A":["Halloween décor","Easter décor","Thanksgiving décor","Wreaths","Garlands","Seasonal table décor","Holiday extension cords"],
  "B1-B":["Old yearbooks","Wedding keepsakes","Baby books","Diplomas","Awards","Scrapbooks","Printed family photos"],
  "B1-C":["Wrapping paper","Ribbon","Greeting cards","Extra printer paper","Binders","Craft glue","Gift boxes","Spare batteries","Extra household bulbs"],
  "B1-D":["Router","Network switch","NVR","UPS battery backup","Ethernet patch cables","Smart-home hubs"],
  "B2-A":["Furnace filters","Air purifier filters","Water filters used by house systems"],
  "B2-B":["Sump-pump parts","Water-softener supplies","Thermostat accessories","Appliance manuals","Warranty paperwork"],
  "B3-A":["Toilet paper","Hand soap","Plunger","Toilet brush","Guest towels","Air freshener"],
  "B4-A":["Pasta maker","Mandoline","Immersion blender accessories","Specialty measuring tools"],
  "B4-B":["Bread machine","Large Dutch oven","Turkey roaster","Pressure canner","Large serving cookware"],
  "B4-C":["Measuring cups","Measuring spoons","Thermometers","Specialty whisks","Pastry tools"],
  "B4-D":["Frequently used specialty appliances","Heavy mixing bowls","Large prep containers"],
  "B5-A":["Punch bowl","Drink dispenser","Chafing dishes","Serving platters","Disposable cutlery"],
  "B5-B":["Spare lids","Meal-prep containers","Large party containers","Cooler inserts"],
  "B6-A":["Duffel bags","Travel pillows","Neck pillows","Luggage scales","Packing organizers"],
  "B6-B":["Sleeping pads","Camping blankets","Camp pillows"],
  "B6-C":["Tent","Camp chairs","Camping stove","Camp cookware","Hiking backpacks","Lanterns"],
  "B7-A":["Birth certificates","Social Security cards","Will / estate papers","Vehicle titles","Home deed copies","Insurance records"],
  "B7-B":["Jewelry","Backup hard drives","Spare house keys","Emergency cash"],
  "M1-A":["Mixer attachments","Dough hook","Whisk attachment","Paddle attachment"],
  "M1-B":["Spatulas","Wooden spoons","Tongs","Ladles","Peelers","Can opener"],
  "M1-C":["Saucepans","Frying pans","Dutch oven","Lids","Everyday stock pot"],
  "M1-D":["Dish soap","Dishwasher tabs","Sponges","Sink brush","Dish towels"],
  "M1-E":["Flatware","Measuring spoons","Kitchen scissors","Prep gadgets"],
  "M1-F":["Everyday leftovers containers","Matching lids","Snack containers","Lunch prep containers"],
  "M1-G":["Cutting boards","Sheet pans","Cooling racks","Pizza pans"],
  "M1-H":["Loaf pans","Dutch oven for bread","Proofing baskets / bannetons","Large mixing bowls","Cooling racks","Sheet pans","Baking mats","Bread storage container"],
  "M1-L":["Kitchen scale","Bench scraper","Dough whisk","Bread lame / scoring blades","Instant-read thermometer","Measuring cups","Measuring spoons","Pastry brush","Rolling pin","Parchment paper","Reusable bowl covers","Dough proofing cloths"],
  "M1-I":["Plates","Bowls","Glasses","Mugs","Everyday serving bowls"],
  "M1-J":["Holiday serving pieces","Specialty glassware","Rarely used dishes"],
  "M1-K":["Fridge filters","Water-filter backups","Food-storage accessories"],
  "M2-A":["Cereal","Snacks","Pasta","Rice","Canned goods","Coffee","Tea"],
  "M2-B":["Bulk flour","Sugar","Bulk snacks","Extra canned goods","Backstock condiments"],
  "M2-C":["Cases of drinks","Paper towels","Large pantry appliances","Bulk pet or household consumables"],
  "M3-A":["Coats","Light jackets","Rain jackets"],
  "M3-B":["Sunglasses","Reusable shopping bags","Sunscreen","Dog leashes","Backpacks"],
  "M3-C":["Boots","Everyday shoes","Slippers"],
  "M4-A":["Guest hand towels","Hand lotion","Extra soap","Bathroom cleaner","Air freshener"],
  "M5-A":["Label-approved spa chemicals","Sealed maintenance products approved for indoor conditioned storage"],
  "M5-B":["Test strips","Spa thermometer","Filter-cleaning accessories","Small pool brushes"],
  "M5-C":["Extra paper goods","Lightweight household refills","Seasonal laundry backups"],
  "M5-D":["Bathroom cleaner","Stainless cleaner","Stone cleaner","Disinfecting wipes"],
  "M5-E":["Trash bags","Dish soap refills","Hand-soap refills","Light bulbs","Batteries"],
  "M5-F":["Microfiber cloths","Scrub brushes","Dusting tools","Magic erasers"],
  "M5-G":["Stain remover","Lint rollers","Garment bags","Ironing accessories"],
  "M5-H":["Dish gloves","Small sink caddy","Pipe-safe drain tools"],
  "M5-I":["Pool towels","Cleaning towels","Mop heads","Bulky cleaning tools"],
  "M6-A":["Board games","Playing cards","Dice games","Family puzzles"],
  "M6-B":["Books","Remote controls","Game accessories","Family photo books"],
  "M6-C":["LEGO bins","Dress-up accessories","Nerf gear","Indoor active-play toys"],
  "G1-A":["Hammer","Screwdrivers","Pliers","Adjustable wrench","Tape measure"],
  "G1-B":["Safety glasses","Work gloves","Lubricants","Tool manuals"],
  "G1-C":["Hex keys","Precision screwdrivers","Small pliers"],
  "G1-D":["Drill bits","Saw blades","Measuring tape","Squares"],
  "G1-E":["Picture-hanging hardware","Hooks","Drywall anchors","Machine screws"],
  "G1-F":["Glue gun","Staple gun","Caulk gun","Heat gun accessories"],
  "G1-G":["Drill","Impact driver","Circular saw","Battery chargers"],
  "G1-H":["Shop vacuum accessories","Jacks","Large clamps"],
  "G2-A":["Fishing licenses","Reels","Lures","Bike helmets","Sports balls"],
  "G2-B":["Life jackets","Long-handled nets","Fishing rods"],
  "G2-C":["Heavy tackle bags","Portable sports gear","Outdoor game bases"],
  "G3-A":["Bug spray","Sunscreen","Gardening gloves","Flashlights"],
  "G3-B":["Small extension cords","Outdoor wipes","Work towels"],
  "G4-A":["Cookout drinks","Extra milk","Party beverages","Condiments"],
  "G4-B":["Bulk meat","Frozen meals","Holiday leftovers","Party ice"],
  "G5-A":["Car-care towels","Small covers","Tie-down straps"],
  "G5-B":["Car ramps","Tall automotive gear","Folding equipment"],
  "G5-C":["Snow shovel","Heavy automotive supplies","Large seasonal gear"],
  "U1-A":["Folded clothes","Off-season clothes","Small hobby bins"],
  "U1-B":["Shirts","Jackets","Dress clothes"],
  "U1-C":["Shoes","Extra pillows","Small luggage"],
  "U2-A":["Bath towels","Hand towels","Extra toilet paper","Spare toiletries"],
  "U2-B":["Daily shampoo","Soap","Toothpaste","Nail clippers"],
  "U2-C":["Bathroom cleaner","Toilet cleaner","Spare trash bags"],
  "U3-A":["Tablet stands","Camera gear","Game controllers","Tech cases"],
  "U3-B":["Charging cables","Spare adapters","SD cards","Battery packs"],
  "U4-A":["Sheet sets","Pillowcases","Mattress protectors"],
  "U4-B":["Throws","Light blankets","Electric blankets"],
  "U4-C":["Comforters","Duvets","Extra pillows"],
  "U5-A":["Air purifier","White-noise machines","Humidifiers","Diffusers"],
  "U5-B":["Sleep masks","Diffuser refills","Night lights","Extra humidifier parts"],
  "U6-A":["Electric razor","Trimmer guards","Daily cologne","Daily deodorant"],
  "U6-B":["Daily skincare","Hair products","Makeup","Contact solution"],
  "U6-C":["First-aid basics","Personal-care backups","Travel toiletries"],
  "U6-D":["Hair dryer","Curling iron","Nail kit","Extra grooming tools"],
  "U7-A":["Everyday hanging clothes","Formalwear","Military uniforms"],
  "U7-B":["T-shirts","Shorts","Workout clothes"],
  "U7-C":["Sweaters","Jeans","Pajamas"],
  "U7-D":["Belts","Handbags","Shoes","Hats"],
  "U7-E":["Laundry refills","Extra hangers","Garment bags"],
  "U7-F":["Delicates wash","Stain tools","Ironing supplies"],
  "U8-A":["Folded clothes","Off-season clothes","Personal storage bins"],
  "U8-B":["Hanging clothes","Dress clothes"],
  "U8-C":["Shoes","Extra pillows","Hobby gear"],
  "O1-A":["Rake","Shovel","Broom","Long-handled garden tools"],
  "O1-B":["Hand pruners","Small garden tools","Extension cords"],
  "O1-C":["Outdoor repair tools","Potting supplies","Project staging"],
  "O1-D":["Plant ties","Garden gloves","Hose nozzles","Small outdoor hardware"],
  "O1-E":["Wheelbarrow","Hose reel","Large yard equipment","Outdoor games"],
  "O2-A":["Pre-emergent","Weed killer","Insect control products"],
  "O2-B":["Fertilizer","Plant food","Grass seed","Soil amendments"],
  "O3-A":["Pool toys","Floaties","Vacuum hose","Skimmer net","Pool cover accessories"],
  "O3-B":["Replacement filters","Pump accessories","Pool vacuum parts"],
  "O4-A":["Test kit","Test-strip backups","Small skimmer parts","Brush heads"],
  "O4-B":["Hose adapters","Winter plugs","Fittings","Seasonal caps"],
  "O5-A":["Outdoor tablecloth","Citronella candles","Serving trays","Outdoor paper goods"],
  "O6-A":["Tongs","Spatulas","Grill brush"],
  "O6-B":["Meat thermometer","Skewers","Injector","Basting brush"],
  "O6-C":["Foil","Butcher paper","Grill gloves","Disposable drip pans"]
};
function suggestedItemsForSub(subCode){ return SUBLOCATION_SUGGESTIONS[subCode] || []; }

const SUBLOCATION_REVIEW = {
  "B1-C":["Fireworks are listed in the old inventory, but they are intentionally not assigned to a storage location here. Choose storage that follows the product label, local rules, and fire-safety guidance."]
};
function plannedItemsForSub(subCode){ return SUBLOCATION_ITEMS[subCode] || []; }

const sublocByCode = Object.fromEntries(SUBLOCATIONS.map(x=>[x.code,x]));
function sublocationsFor(locationCode){ return SUBLOCATIONS.filter(x=>x.location===locationCode); }


const MOVING_STEPS = [
  {id:"mv-kitchen",title:"Kitchen & pantry",why:"Start here. These are the highest-use spaces on day one.",codes:["M1","M2"]},
  {id:"mv-laundry",title:"Laundry room",why:"Set the cleaning and laundry homes before random supplies spread through the house.",codes:["M5"]},
  {id:"mv-baths",title:"Bathrooms",why:"Make every bathroom functional before unpacking decorative or long-term items.",codes:["M4","U2","U6","B3"]},
  {id:"mv-bedrooms",title:"Bedrooms & master closet",why:"Give clothes, linens, tech, and sleep items a home early.",codes:["U1","U3","U4","U5","U7","U8"]},
  {id:"mv-entry",title:"Entry coat closet",why:"Create one landing zone for shoes, coats, bags, hats, gloves, and umbrellas.",codes:["M3"]},
  {id:"mv-garage",title:"Garage",why:"Keep the workbench as staging until categories are visible, then place tools and bulky gear.",codes:["G1","G2","G3","G5"]},
  {id:"mv-basement-kitchen",title:"Basement kitchen & peninsula",why:"Move specialty appliances and entertaining overflow out of the main kitchen.",codes:["B4","B5"]},
  {id:"mv-bulk",title:"Under-stairs & basement storage",why:"Do bulky, seasonal, sentimental, and long-term storage after daily-use rooms are settled.",codes:["B6","B1","B2","B7"]},
  {id:"mv-game",title:"Game room",why:"Finish recreation storage once the practical rooms are working.",codes:["M6"]},
  {id:"mv-outdoor",title:"Shed, pool & outdoor kitchen",why:"Last pass: outdoor gear, pool equipment, grilling, and yard supplies.",codes:["O1","O2","O3","O4","O5","O6","O7","O8"]}
];
